name: Update Gist

on:
  push:
    paths:
      - dailyquote.lua
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload file to Gist
        run: |
          MARKDOWN_FILE="dailyquote.md"
          LUA_FILE="dailyquote.lua"
          echo '' >> "$MARKDOWN_FILE"
          echo '```space-lua' >> "$MARKDOWN_FILE"
          cat "$LUA_FILE" >> "$MARKDOWN_FILE"
          echo '```' >> "$MARKDOWN_FILE"

          # Define filename correctly for Gist
          FILENAME="$MARKDOWN_FILE"
          FILE_CONTENT=$(cat "$MARKDOWN_FILE" | jq -Rs .)

          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/c81be7d9746d3be6234b8f6a9c78cabc \
            -d "{\"files\": {\"$FILENAME\": {\"content\": $FILE_CONTENT}}}"
