name: Update Gist

on:
  push:
    paths:
      - dailyquote.md
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload file to Gist
        run: |
          FILE_PATH="dailyquote.md"
          FILENAME=$(basename "$FILE_PATH")
          FILE_CONTENT=$(cat "$FILE_PATH" | jq -Rs .)

          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/c81be7d9746d3be6234b8f6a9c78cabc \
            -d "{\"files\": {\"$FILENAME\": {\"content\": $FILE_CONTENT}}}"
